<?php

/**
 * @file
 * Provides Facebook Like Application functionality.
 */

/**
 * Local Task url.
 */
define('FB_LIKE_APP_TASK', 'app');

/**
 * Facebook Like Application "Like" state.
 */
define('FB_LIKE_APP_LIKE', 'like');

/**
 * Facebook Like Application "Liked" state.
 */
define('FB_LIKE_APP_LIKED', 'liked');

/**
 * Facebook Like Application "Closed" state.
 */
define('FB_LIKE_APP_CLOSED', 'closed');

/**
 * Facebook Like Application "Maintenance" state.
 */
define('FB_LIKE_APP_MAINTENANCE', 'maintenance');

/**
 * Load internal helper functions.
 */
require dirname(__FILE__) . '/fb_like_app.inc';


/**
 * Implements hook_init().
 */
function fb_like_app_init() {
  global $language, $conf, $fb_like_app;

  // Parse signed request and language from Facebook page.
  if ( arg(0) == 'node' && is_numeric(arg(1)) && arg(2) == FB_LIKE_APP_TASK ) {
    $node = node_load(arg(1));

    // Get field data from node.
    $field_app_id = field_get_items('node', $node, 'field_app_id');
    $field_app_secret = field_get_items('node', $node, 'field_app_secret');

    $fb_like_app->app_id = $field_app_id[0]['value'];
    $fb_like_app->app_secret = $field_app_secret[0]['value'];

    // Parse the signed request.
    if ( isset($_REQUEST['signed_request']) ) {
      $fb_like_app->parsed_request = fb_like_app_parse_signed_request($_REQUEST['signed_request'], $fb_like_app->app_secret);

      // Check if page is liked.
      if ( isset($fb_like_app->parsed_request['page']['liked']) ) {
        $fb_like_app->liked = $fb_like_app->parsed_request['page']['liked'];
      }

      // Get user locale.
      if ( isset($fb_like_app->parsed_request['user']['locale']) ) {
        $fb_like_app->locale = $fb_like_app->parsed_request['user']['locale'];
      }
    }

    // Override the current language with the language set from Facebook.
    if ( isset($fb_like_app->locale) && variable_get('fb_like_app_override_language', TRUE) ) {
      $lang = fb_like_app_lang_map($fb_like_app->locale);
      $languages = language_list();
      if ( isset($languages[$lang]) ) {
        $language = $languages[$lang];
      }
    }

    // If liked state was not set from the signed_request, see our own mode.
    if ( !isset($fb_like_app->liked) ) {
      $fb_like_app->liked = 0;
    }

    $conf['cache'] = FALSE;
  }
}

/**
 * Implements hook_perm().
 */
function fb_like_app_permission() {
  return array(
    'view fb like app' => array(
      'title' => t('View Facebook Like Applications'),
      'description' => t('Ability to view the rendered Facebook Like Application page'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function fb_like_app_menu() {
  return array(
    'node/%node/' . FB_LIKE_APP_TASK => array(
      'title' => 'Like Application',
      'page callback' => 'fb_like_app_page',
      'page arguments' => array(1, 3),
      'access callback' => '_fb_like_app_access',
      'access arguments' => array(1),
      'type' => MENU_LOCAL_TASK,
    ),
    'fb_like_app/channel' => array(
      'page callback' => 'fb_like_app_channel',
      'access arguments' => array('view fb like app'),
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * Menu Access Callback.
 */
function _fb_like_app_access($node) {
  if ( $node->type == 'fb_like_app' ) {
    return user_access('view fb like app');
  }

  return FALSE;
}

/**
 * Implements hook_theme().
 */
function fb_like_app_theme() {
  return array(
    'fb_like_app' => array(
      'variables' => array('node' => NULL, 'type' => NULL),
      'template' => 'fb-like-app',
      'path' => drupal_get_path('module', 'fb_like_app') . '/theme',
      'file' => 'theme.inc',
    ),
    'fb_like_app_admin' => array(
      'variables' => array('node' => NULL),
      'template' => 'fb-like-app-admin',
      'path' => drupal_get_path('module', 'fb_like_app') . '/theme',
      'file' => 'theme.inc',
    ),
    'fb_like_app_like' => array(
      'variables' => array('node' => NULL),
      'template' => 'fb-like-app-like',
      'path' => drupal_get_path('module', 'fb_like_app') . '/theme',
      'file' => 'theme.inc',
    ),
    'fb_like_app_liked' => array(
      'variables' => array('node' => NULL),
      'template' => 'fb-like-app-liked',
      'path' => drupal_get_path('module', 'fb_like_app') . '/theme',
      'file' => 'theme.inc',
    ),
    'fb_like_app_closed' => array(
      'variables' => array('node' => NULL),
      'template' => 'fb-like-app-closed',
      'path' => drupal_get_path('module', 'fb_like_app') . '/theme',
      'file' => 'theme.inc',
    ),
    'fb_like_app_maintenance' => array(
      'variables' => array('node' => NULL),
      'template' => 'fb-like-app-maintenance',
      'path' => drupal_get_path('module', 'fb_like_app') . '/theme',
      'file' => 'theme.inc',
    ),
  );
}

/**
 * Page Callback: Facebook Like Application.
 */
function fb_like_app_page($node, $type = NULL) {
  print theme('fb_like_app', array('node' => $node, 'type' => $type));
}

/**
 * Page Callback: Facebook Channel File.
 *
 * @see https://developers.facebook.com/docs/reference/javascript/
 */
function fb_like_app_channel() {
  $cache_expire = 60*60*24*365;
  header("Pragma: public");
  header("Cache-Control: max-age=" . $cache_expire);
  header('Expires: ' . gmdate('D, d M Y H:i:s', time() + $cache_expire) . ' GMT');
  print '<script src="//connect.facebook.net/en_US/all.js"></script>';
}
